dm: check if all dm sources include config.h
In debug build, add a config_check_filename_o variable to each
dm source, and generate additional source referencing the above. If
any source file does not include config.h, there will be a link
error in the form
undefined reference to `config_check_block_swap_hashtable_o'

For http-parser, check that defensive.h has been included.